                            
/programa1: programa1.o
        gcc -o  programa1  programa1.o
programa1.o: programa1.s 
        as  -o programa1.o programa1.s
clean:
        rm programa1 programa1.o
        rm programa2 programa2.o

programa2: programa2.o
        gcc -o  programa2  programa2.o
programa2.o: programa2.s 
        as  -o programa2.o programa2.s
